<?php

/**
 * @file
 * Simple, extensible user import from a CSV file.
 */

/**
 * Implementation of hook_install().
 */
function uif_install() {
  drupal_set_message('User import framework module installed. You can now <a href="' . url('admin/people/uif') . '">import users</a>.');
}

/**
 * Implementation of hook_uninstall().
 */
function uif_uninstall() {
  db_query('DELETE FROM {variable} WHERE name LIKE :uif', array(':uif' => 'uif_' . '%'));
}

